name: iOS Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 'latest' # or specify a specific version
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS app
        run: flutter build ios
